### ISSUE TITLE
Home Controller active page

### ISSUE THREAD

**Issue by Karyum** [facn2/judgement-day#20]
https://github.com/facn2/judgement-day/blob/master/src/controllers/home.js#L2

Do you guys need this activePage object ??
i know that i merged this but im just checking.

**Comment by matthewdking** [comment]
@Karyum not sure we will look into it now

**Comment by Karyum** [comment]
cause that i just passing data to the hbs in this case the data is home: true which what we used in the workshop so we can set the underlines in the navbar for which papge we  were on, so i your guys case you kidna dont need un less you gonna be doing something like that
